FROM golang:1.19 AS building

COPY . /building
WORKDIR /building

RUN make frps

FROM alpine:3

COPY --from=building /building/bin/frps /usr/bin/frps

RUN apk add curl

HEALTHCHECK --interval=1m --timeout=30s --retries=3 CMD curl --fail http://localhost:7001/healthz || exit 1

ENTRYPOINT ["/usr/bin/frps"]
